version: '3.4'

services:
  x21146331xtktoken:
    image: x21146331/xtktokendist
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    env_file:
      - .env
    ports:
      - 8090:8080
