version: '3.4'

services:
  x21146331xtktoken:
    image: x21146331xtktoken
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8090:8080
